config/routes.rb
MuicForum::Application.routes.draw do

  	resources :boards do
		resources :topics
  	end

  	resources :topics do
  		resources :comments
  	end  	

	resources :users
	resources :sessions, only: [:new, :create, :destroy]
	root  'boards#index'
	
	match '/signup',  to: 'users#new',            via: 'get'
    match '/signin',  to: 'sessions#new',         via: 'get'
    match '/signout', to: 'sessions#destroy',     via: 'delete'
	match '/help',    to: 'static_pages#help',    via: 'get'
	match '/tagcloud', to: 'static_pages#tagcloud', via: 'get'
	match '/about',   to: 'static_pages#about',   via: 'get'
	match '/contact', to: 'static_pages#contact', via: 'get'
	match '/tags/:tag', to: 'topics#index', as: :tag, via: 'get'
	match '/search', to: 'topics#search', via: 'get'
	match '/topics/:id/like', to: 'topics#like', via: 'post'
	match '/topics/:id/unlike', to: 'topics#unlike', via: 'post'
	match '/like',	to: 'static_pages#like', 	via: 'get'
	match '/boardpanel', to:'boards#boardpanel', via: 'get'
	match '/users/:id/admin', to: 'users#admin', via: 'post'
	match '/usersearch', to: 'users#usersearch', via:'get'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	acts_as_taggable_on :keyword
	acts_as_votable

	belongs_to :user
	belongs_to :board
	has_many :comments , dependent: :destroy
	default_scope -> { order('updated_at DESC') }
	validates :title, presence: true, length: { maximum: 150 }
	validates :user_id, presence: true
	validates :board_id, presence: true
	validates :subtitle, presence: true
	

def self.search(search)
	if search  
    	where('title LIKE ?', "%#{search}%")  
    else  
     	scoped  
  	end  
end


end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def search
  	if(params[:search] && params[:search] != '')
  		@topics = Topic.search(params[:search]).order("updated_at DESC").paginate(per_page: 15, page: params[:page])
  	end
  end

  def like
  	@topic = Topic.find(params[:id])
  	@topic.liked_by current_user
  	@users = @topic.votes.up.by_type(User).voters
  		
  	respond_to do |format|
      format.html { redirect_to board_topic_path(@topic.board, @topic) }
      format.js
    end 
  end

  def unlike
  	@topic = Topic.find(params[:id])
  	@topic.unliked_by current_user
  	@users = @topic.votes.up.by_type(User).voters

  	respond_to do |format|
      format.html { redirect_to board_topic_path(@topic.board, @topic) }
      format.js
    end

  end

  # GET /topics
  # GET /topics.json
  def index
    if(params[:tag])
    	@topics = Topic.tagged_with(params[:tag]).paginate(per_page: 15, page: params[:page])
  	else
    	@topics = Topic.paginate(per_page: 15, page: params[:page])
 	end
end

  # GET /topics/1
  # GET /topics/1.json
  def show
  	load_board
  	@topic = Topic.find(params[:id])
  	@topic.board = @board
  	@comments = @topic.comments
  	@users = @topic.votes.up.by_type(User).voters
  	@topic.keyword_list = @topic.keyword_list[0..4]
  end


  # GET /topics/new
  def new
  	load_board
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  	@topic.keyword_list = @topic.keyword_list[0..4]
  end

  # POST /topics
  # POST /topics.json
  def create
  	load_board
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    @topic.board = @board
    @topic.keyword_list = @topic.keyword_list[0..4]


    if current_user && @topic.save
  		flash[:success] = "Topic was successfuly created."
  		respond_to do |format|
  			format.html { redirect_to :controller => 'topics', :action => 'show', :id => @topic.id }
  	    	format.js
    	end 
  	else
  		render action: "new"
  	end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
      if @topic.update(topic_params)
      	flash[:success] = "Topic was successfuly updated."
      	redirect_to board_topic_path(@topic.board.id, @topic.id)
      else

      end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
  	@board = @topic.board
    @topic.destroy
    flash[:success] = "Topic was successfuly deleted."
    redirect_to :controller => 'boards', :action => 'show', :id => @board.id 
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :subtitle, :user_id, :board_id, :keyword_list)
    end

    def load_board
    	if Board.exists?(params[:board_id])
    		@board = Board.find(params[:board_id])
    	end

    	unless @board
    		redirect_to(boards_path, :notice => "Please specify a valid board" )
    	end
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for([@board, @topic]) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label "Topic" %>
    <%= f.text_field :title, class:"form-control" %>
  </div>

  	<div class="field">
	  <%= f.label :keyword_list, "Tags (separated by commas, only 5 tags are allowed, and do not include any symbol.)" %>
	  <%= f.text_field :keyword_list, class:"form-control" %>
	</div>
 
  <div class="field">
    <%= f.label "Content" %>
    <%= f.text_area :subtitle, :size => "60x10", class:"form-control" %>
  </div>
  
  <div class="actions" style="text-align: center;">
    <%= f.submit :as => "Create Post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/topics/_like.html.erb
<%= form_tag url_for(:controller => "topics", :action => 'unlike'), class: "likebutton", remote: true do %>
	<%= button_tag(:name => nil, class: "btn btn-default likebuttontag") do %>
		<i class="fa fa-plus-circle fa-3 blueicon" id="likeBut" style="zoom: 3; margin-left: -4px; margin-top: -2px;"></i>
	<%end%>
<% end %>

app/views/topics/_topic.html.erb
<% if topic.board %> 
	<li>
	  <span class="content"><h4 style="text-decoration: none;"><%= link_to topic.title.truncate(60), board_topic_path(topic.board_id, topic) %></h4></span>
	  <span class="timestamp">
	    Posted <%= time_ago_in_words(topic.created_at) %> ago.
	  </span>
	</li>

<% end %>

app/views/topics/_unlike.html.erb
<%= form_tag url_for(:controller => "topics", :action => 'like'), class: "likebutton", remote: true do %>
	<%= button_tag(:name => nil, class: "btn btn-warning likebuttontag") do %>
		<i class="fa fa-plus-circle fa-3 greyicon" id="likeBut" style="zoom: 3; margin-left: -4px; margin-top: -2px;"></i>
	<%end%>
<% end %>

app/views/topics/_usercomment.html.erb
<% @count = 0 %>
<% @topic.comments.each do |comment| %>
	<% @count = @count + 1 %>
	<div class="panel panel-default" id="comment-<%= comment.id%>">
		<div id="comment">
			Comment #<%= @count %>
		</div>
		<% if( (current_user.id == comment.user.id || current_user.admin?) && !comment.dstatus ) %>
			<div class="btn-group" style="float: right; margin-right: 17px;">
			   	<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" >
					<span class="caret"></span>
					</button>		
			 	<ul class="dropdown-menu" role="menu">
				    <li>
						<a href data-toggle="modal" 
						   data-target="#<%= comment.id %>edit">
						   <i class="fa fa-pencil"></i> Edit
						</a>
				    </li>
				    <li>
				    	<a href data-toggle="modal" 
						   data-target="#<%= comment.id %>delete">
						   <i class="fa fa-trash-o"></i> Delete
						</a>
		            </li>
			  	</ul>
			</div>
		<% end %>
		
	 	<div class="panel-body" style="margin-top: 2.5em">
	 		<% if comment.dstatus %>
			<div style="color: #CCC; margin-bottom: 2em;">This comment has been deleted.</div>
	 		<% else%>
        	<div class="well" ><%=comment.content%></div>
            <% end %>
        	<br/>
	  	</div>
	  	<div class="panel-footer">
	  	<div style="margin-top: 5px;">
		  	by <%= link_to comment.user.name, comment.user %> <br/>
		    <div style="color: #bbb;">Posted At <%= comment.created_at.time.localtime.to_formatted_s(:db)%></div>
	    </div>
	  </div>
	</div>

	<!-- delete comment Modal -->
	<div class="modal fade" id="<%= comment.id %>delete" tabindex="-65" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	        <h4 class="modal-title" id="myModalLabel">Delete comment</h4>
	      </div>
	      <div class="modal-body">
	       	Are you sure?
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	        <%= link_to [@topic, comment], method: :delete, remote: true, class: "btn btn-danger" do %>
									 Delete
			<% end %>
	      </div>
	    </div>
	  </div>
	</div>

	<!-- edit Modal -->
	<div class="modal fade" id="<%= comment.id %>edit" tabindex="-65" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	        <h4 class="modal-title" id="myModalLabel">Edit comment</h4>
	      </div>
	      <div class="modal-body">
	      	<%= form_for [@topic, comment], remote: true  do |f| %>
	       		<div class="field">
	    		<%= f.label 'Edit Comment' %>
	    		<%= f.text_area :content, class:"form-control" %>
	  		</div>
	      </div>
	      <div class="modal-footer">
		        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
				<%= f.submit "Submit", class: "btn btn-primary", style: "width :auto;" %>
	        <% end %>
	      </div>
	    </div>
	  </div>
</div>
<% end %>
 

app/views/topics/_userlist.html.erb
<div id="userlist">
	<% if users.any? %>
		<div class="likelist" >
			<% users.each do |user|%>
				<% if(users.last != user) %>
					<%= link_to user.name, user %>, 
				<% else %>
					<%= link_to user.name, user %>
				<% end %>
			<% end %>
		</div>
	<% end %>
</div>

app/views/topics/_votesize.html.erb
<i class="fa fa-heart" ></i> <%= @topic.votes.size %>

app/views/topics/destroy.js.erb
//var str="<%= escape_javascript(render('topics/unlike')) %>";
//var obj = document.getElementById('likeForm');
//alert(str);
//obj.innerHTML=str;
$("#likeForm").html("<%= escape_javascript(render('topics/unlike')) %>")
$("#likes").html("<%= escape_javascript(render('topics/votesize')) %>")
$("#userlist").html("<%= escape_javascript(render('topics/userlist', users: @users)) %>")

app/views/topics/index.html.erb
<h1 id="page_title"><%= params[:tag] %></h1>
<p id="notice"><%= notice %></p>
<table class = "table">
<div style="float: right;"><%= will_paginate @topics, renderer: BootstrapPagination::Rails %></div> 
  <tr>
  	<thead>
	    <th style="width: 650px;"><i class="fa fa-list-ul"> Topic / Author</th>
	    <th style="width: 100px;">Last Reply</th>
	    <th style="text-align: center;">Number of Replies</th>
    </thead>
  </tr>
<% @topics.each do |topic| %>
  <tr>
    <td>
      <div id="post-link"><%= link_to topic.title, board_topic_path(topic.board, topic), id: "post-link"%></div>
      <div id="user-name-post-index"><span>by <%= link_to topic.user.name, topic.user %></span></div>
    </td>
    <td>
      <% comment = topic.comments.last %>
      <% if comment%>
      	<span class="timestamp">
    		<%= comment.created_at.time.localtime.to_formatted_s(:db) %>
  		</span>
      <% else %>
      	<span class="timestamp">
    	 	<%= topic.created_at.time.localtime.to_formatted_s(:db) %>
  		</span>
      <% end %>

    </td>
    <td style="text-align:center;">
      <%=  topic.comments.count%>
    </td>
  </tr>
<% end %>
</table> 
<div style="float: right;"><%= will_paginate @topics, renderer: BootstrapPagination::Rails %></div> 
<br/>

app/views/topics/like.js.erb
//var str="<%= escape_javascript(render('topics/like')) %>";
//alert(str);
//var obj = document.getElementById('likeForm');
//obj.innerHTML=str;

$("#likeForm").html("<%= escape_javascript(render('topics/like')) %>")
$("#likes").html("<%= escape_javascript(render('topics/votesize')) %>")
$("#userlist").html("<%= escape_javascript(render('userlist', users: @users)) %>")

app/views/topics/new.html.erb
<h1 id="page_title">New Topic</h1>
<ol class="breadcrumb">
  <li><%= link_to 'Home', boards_path %></li>
  <li><%= link_to @board.title, @board %></li>
  <li>New Topic</li> 
</ol>
 
<%= render 'form' %>
 

app/views/topics/search.html.erb
 <h1 id="page_title"><%= params[:search] %></h1>
<p id="notice"><%= notice %></p>
<table class = "table">
<div style="float: right;"><%= will_paginate @topics, renderer: BootstrapPagination::Rails %></div> 
  <tr>
    <th style="width: 650px;"><i class="fa fa-list-ul"> Topic / Author</th>
    <th style="width: 100px;">Last Reply</th>
    <th>Number of Replies</th>
  </tr>
<% @topics.each do |topic| %>
  <tr>
    <td>
      <div id="post-link"><%= link_to topic.title, board_topic_path(topic.board, topic), id: "post-link"%></div>
      <div id="user-name-post-index"><span>by <%= link_to topic.user.name, topic.user %></span></div>
    </td>
    <td>
      <% comment = topic.comments.last %>
      <% if comment%>
      	<span class="timestamp">
    		<%= comment.created_at.time.localtime.to_formatted_s(:db) %>
  		</span>
      <% else %>
      	<span class="timestamp">
    	 	<%= topic.created_at.time.localtime.to_formatted_s(:db) %>
  		</span>
      <% end %>

    </td>
    <td>
      <%=  topic.comments.count%>
    </td>
  </tr>
<% end %>
</table> 
<div style="float: right;"><%= will_paginate @topics, renderer: BootstrapPagination::Rails %></div> 
<br/>

app/views/topics/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Home', boards_path %></li>
  <li><%= link_to @board.title, @board %></li>
  <li><%= link_to @topic.title.truncate(30), [@topic.board,@topic] %>
</ol><p id="notice"><%= notice %></p>
 
<div class="panel panel-default">
  	<div class="panel-heading" style="background-color: white;">
	    	<h3 class="panel-title" style="font-size: 30px; color: #586996;"><%= @topic.title.squish.gsub(/(.{50})(?=.)/, '\1 \2') %>
			<div class="delete-post-btn">
			    <% if(current_user.id == @topic.user.id || current_user.admin?) %>
					<div class="btn-group" style="float: right;">
					   	<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" >
    						<span class="caret"></span>
  						</button>		
					  <ul class="dropdown-menu" role="menu">
					    <li><%= link_to edit_board_topic_path(@board, @topic) do%>
								<i class="fa fa-pencil"></i> Edit
							<% end %>
					    </li>
					    <li><a href data-toggle="modal" 
								   data-target="#<%=@topic.id%>deletetopicModal">
								   <i class="fa fa-trash-o"></i> Delete
								</a>
					    </li>
					  </ul>
					</li>
				<% end %>
			</div>
		</h3>
		<p id="tagging">Tags: <%= raw @topic.keyword_list.map { |t| link_to t, tag_path(t) }.join(' ') %></p>
 	 </div>
  	<div class="panel-body" >
    	<%= @topic.subtitle %>
  	</div>
    <div class="panel-footer" style="margin-top: 1.5em;">
		
		<%= render 'like_form' %>

		<div style=" float: left; margin-left: 3px; margin-right: 15px; margin-bottom:10px; margin-top:7px;">
			<span class="badge" style="font-size: 20px;" id="likes">
				<%= render 'votesize' %>
			</span>
		</div>

	    <div style="margin-top: 5px;"> 
			by <%= link_to @topic.user.name, @topic.user %> <br />
		   	<div style="color: #bbb;">Posted at <%= @topic.created_at.time.localtime.to_formatted_s(:db)%></div>
	    </div>
		
		<%= render 'userlist', users: @users %>
		
		
    </div>
</div>

	<div id="commentlist"><%= render 'usercomment' %></div>


<!-- delete topics Modal -->
	<div class="modal fade" id="<%=@topic.id%>deletetopicModal" tabindex="-65" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	        <h4 class="modal-title" id="myModalLabel">Delete topic</h4>
	      </div>
	      <div class="modal-body">
	       	Are you sure?
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	        <%= link_to @topic, method: :delete, class: "btn btn-danger" do%>
									 Delete
			<% end %>
	      </div>
	    </div>
	  </div>
	</div>

<%= form_for([@topic, @topic.comments.build], remote: true) do |f| %>
  <div class="field">
    <%= f.label 'Comment' %>
    <%= f.text_area :content, class:"form-control" %>
  </div>
   <div class="actions" style="text-align: center;">
    <%= f.submit 'Comment',class: "btn btn-primary", style: "width: auto;"%>
  </div>
<% end %>

app/views/topics/unlike.js.erb
$("#likeForm").html("<%= escape_javascript(render('topics/unlike')) %>")
$("#likes").html("<%= escape_javascript(render('topics/votesize')) %>")
$("#userlist").html("<%= escape_javascript(render('userlist', users: @users)) %>")