config/routes.rb
MuicForum::Application.routes.draw do

  	resources :boards do
		resources :topics
  	end

  	resources :topics do
  		resources :comments
  	end  	

	resources :users
	resources :sessions, only: [:new, :create, :destroy]
	root  'boards#index'
	
	match '/signup',  to: 'users#new',            via: 'get'
    match '/signin',  to: 'sessions#new',         via: 'get'
    match '/signout', to: 'sessions#destroy',     via: 'delete'
	match '/help',    to: 'static_pages#help',    via: 'get'
	match '/tagcloud', to: 'static_pages#tagcloud', via: 'get'
	match '/about',   to: 'static_pages#about',   via: 'get'
	match '/contact', to: 'static_pages#contact', via: 'get'
	match '/tags/:tag', to: 'topics#index', as: :tag, via: 'get'
	match '/search', to: 'topics#search', via: 'get'
	match '/topics/:id/like', to: 'topics#like', via: 'post'
	match '/topics/:id/unlike', to: 'topics#unlike', via: 'post'
	match '/like',	to: 'static_pages#like', 	via: 'get'
	match '/boardpanel', to:'boards#boardpanel', via: 'get'
	match '/users/:id/admin', to: 'users#admin', via: 'post'
	match '/usersearch', to: 'users#usersearch', via:'get'

end

app/models/board.rb
class Board < ActiveRecord::Base
	has_many :topics

	validates :title, presence: true
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  def boardpanel
  	@boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  	@board = Board.find(params[:id])
  	@topics = @board.topics.paginate(per_page: 20, page:params[:page])
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

      if @board.save
        flash[:success] = "Board was successfully created"
        redirect_to boardpanel_path
      else
        render 'new' 
      end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
      if @board.update(board_params)
        flash[:success] = "Board was successfully updated."
        redirect_to boardpanel_path
      else
        render 'edit'
      end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
  	@board.topics.each do |topic|
    		topic.keyword_list.remove(topic.keyword_list, parse: true)
    		topic.save
    end
    @boards = Board.all
    if @board.destroy
 		flash[:success] = "Board was successfully deleted"
 		respond_to do |format|
      		format.html { redirect_to boardpanel_path }
     		format.js
    	end 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:title, :subtitle)
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_board.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @board.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @board.subtitle %>
</p>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>

app/views/boards/_boardlist.html.erb
<table class="table table-hover" >
			<thead>
				<tr>
					<th style="width: 40%;">
						Title
					</th>
					<th>
						Subtitle
					</th>
					<th>Action</th>
				</tr>

			</thead>
		<% if @boards.any? %>
		  <% @boards.all.each do |board| %>
		  		<tr style="background-color:#f2f2f2;">
				    <td><%= link_to board.title, edit_board_path(board), class: "fill-div" %></td>
				    <td>
				    	<%= board.subtitle %>
				    </td>
				    <td>
						<button class="btn btn-danger" data-toggle="modal" 
						   data-target="#<%= board.id %>deleteModal">
						   <i class="fa fa-trash-o"></i> Delete
						</button>
					</td>
				</tr>
		
			<!-- Modal -->
				<div class="modal fade" id="<%= board.id%>deleteModal" tabindex="-65" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				  <div class="modal-dialog">
				    <div class="modal-content">
				      <div class="modal-header">
				        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				        <h4 class="modal-title" id="myModalLabel">Delete Board</h4>
				      </div>
				      <div class="modal-body">
				       	Are you sure?
				      </div>
				      <div class="modal-footer">
				        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
				        <%= link_to board, method: :delete, remote: true, class: "btn btn-danger" do%>
												 Delete
						<% end %>
				      </div>
				    </div>
				  </div>
				</div>
		  <% end %>
		<% else %>
			<tr style="background-color:#f2f2f2;">
				<td>You have no board.</td>
				<td> </td>
				<td> </td>
			</tr>
		<% end %>
</table>

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	  <div class="field">
	    <%= f.label :title %><br>
	    <%= f.text_area :title, class: "form-control" %>
	  </div>
	  <div class="field">
	    <%= f.label :subtitle %><br>
	    <%= f.text_area :subtitle, class: "form-control" %>
	  </div>
	  <div class="actions">
	    <%= f.submit :as => "Create Board", class: "btn btn-primary", style: "margin-bottom: 5px;"%>
	  </div>

<% end %>

app/views/boards/boardpanel.html.erb
<div class="jumbotron" style="background-color: white;">
	
	<div class="container">
	<div class="container-post-new-message">
		<%= link_to new_board_path, class: "btn btn-primary", style: "float: left; margin-bottom: 8px;" do %>
			<i class="fa fa-plus-square"></i> Create Board 
		<% end %>
	</div>
		<div id="listboard"><%= render 'boardlist' %></div>
	</div>
</div>

app/views/boards/destroy.js.erb
$("#listboard").html("<%= escape_javascript(render 'boardlist' ) %>")

app/views/boards/edit.html.erb
<h1>Editing board</h1>

<%= render 'form' %>

<%= link_to 'Back', boardpanel_path, class: "btn btn-default", style: "width: 100%; float: left;" %>

app/views/boards/index.html.erb
<% if !signed_in? %>
	<div class="center jumbotron">
	  <h1>Welcome to the MUIC</h1>
	  <p>
	    This website is available only for Mahidol University Internation College students.
	  </p>
	  <%= link_to "Sign up now!", new_user_url, class: "btn btn-primary btn-lg" %>
	</div>
<% else %>
	<% if Board.all.any? %>
		<div class="container">
		  <% @boards.each do |board| %>
		  <div class="board-container" style="padding: 0px;" >
			  <div class="panel panel-default">
				  <div class="panel-body">
				    <h2 class="panel-title board" style="color: #586996;"><%= link_to board.title, board, class: "fill-div" %></h2>
				  </div>
				  <div class="panel-footer" style="margin-top: 10px; font-size: 16px; margin-left: 10px; color: #AAA;">
				    <%= board.subtitle %>
	 			  </div>
			  </div>
			 </div>
		  <% end %>
		</div>
	<% else %>
		<% if current_user.admin? %>
			<div class="center jumbotron">
		  <h1>You have no board !!</h1>
		  <p>
		    Please click button below to create board.
		  </p>
		  <%= link_to "Create board", new_board_path, class: "btn btn-primary btn-lg", style: "margin-left: -40px;" %>
		</div>
		<% end %>
	<% end %>
	  
<% end %>

app/views/boards/new.html.erb
<h1>New board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path, class: "btn btn-default", style: "width: 100%; float: left;" %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>
<ol class="breadcrumb" style="margin-top: -10px;">
  <li><%= link_to 'Home', boards_path %></li>
  <li><%= link_to @board.title, @board %></li>
</ol>


<div class="container-post-new-message">
	<%= link_to new_board_topic_url(@board), class: "btn btn-primary", style: "float: left; margin-bottom: 8px;" do %>
		<i class="fa fa-plus-square"></i> New Topic 
	<% end %>

	<div style="margin: 0px; float: right;">
		<%= will_paginate @topics, renderer: BootstrapPagination::Rails %>
	</div>
</div>

  				
<table class="table">
  <tr>
  <thead>
    <th style="width: 650px;"><i class="fa fa-list-ul"></i> Topic / Author</th>
    <th style="width: 110px;"><i class="fa fa-edit"></i> Last Reply</th>
    <th style="text-align: center;"><i class="fa fa-comments"></i> Number of Replies</th>
  </thead>
  </tr>
<% if @topics.any? %>
	<% @topics.each do |topic| %>
	  <tr>
	    <td>
	      <div id="post-link"><%= link_to topic.title.truncate(60), board_topic_path(:board_id => @board, :id =>  topic), id: "post-link"%></div>
	      <div id="user-name-post-index"><span>by <%= link_to topic.user.name, topic.user %></span></div>
	    </td>
	    <td>
	      <% comment = topic.comments.last %>
	      <% if comment%>
	      	<span class="timestamp">
	    		<%= comment.created_at.time.localtime.to_formatted_s(:db) %>
	  		</span>
	      <% else %>
	      	<span class="timestamp">
	    	 	<%= topic.created_at.time.localtime.to_formatted_s(:db) %>
	  		</span>
	      <% end %>

	    </td>
	    <td style="text-align: center;">
	      <%=  topic.comments.count%>
	    </td>
	  </tr>
	<% end %>
	</table> 
<% else %>
	<tr>
		<td>
			Board is empty!
		</td>
	</tr>
	</table>
<% end %>
<div style="margin: 0px; float: right;">
		<%= will_paginate @topics, renderer: BootstrapPagination::Rails %>
</div>
<%= link_to new_board_topic_url(@board), class: "btn btn-primary" do %>
		<i class="fa fa-plus-square"></i> New Topic 
	<% end %>