config/routes.rb
MuicForum::Application.routes.draw do

  	resources :boards do
		resources :topics
  	end

  	resources :topics do
  		resources :comments
  	end  	

	resources :users
	resources :sessions, only: [:new, :create, :destroy]
	root  'boards#index'
	
	match '/signup',  to: 'users#new',            via: 'get'
    match '/signin',  to: 'sessions#new',         via: 'get'
    match '/signout', to: 'sessions#destroy',     via: 'delete'
	match '/help',    to: 'static_pages#help',    via: 'get'
	match '/tagcloud', to: 'static_pages#tagcloud', via: 'get'
	match '/about',   to: 'static_pages#about',   via: 'get'
	match '/contact', to: 'static_pages#contact', via: 'get'
	match '/tags/:tag', to: 'topics#index', as: :tag, via: 'get'
	match '/search', to: 'topics#search', via: 'get'
	match '/topics/:id/like', to: 'topics#like', via: 'post'
	match '/topics/:id/unlike', to: 'topics#unlike', via: 'post'
	match '/like',	to: 'static_pages#like', 	via: 'get'
	match '/boardpanel', to:'boards#boardpanel', via: 'get'
	match '/users/:id/admin', to: 'users#admin', via: 'post'
	match '/usersearch', to: 'users#usersearch', via:'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Mahidol University International College</a>
    by Ronnakrit K.
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation" style="height: 50px">
	<div class="navbar-inner">
	  <div class="container-fluid" style="width: 1100px;">
	    <div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
			    <span class="icon-bar"></span>
			    <span class="icon-bar"></span>
			    <span class="icon-bar"></span>
			 </button>
			 <div class="navbar-brand" style="padding-right: 0px;"><%= link_to image_tag("muiclogo-big.png", alt: "Mahidol University Internation College", id: "logoimg"),  root_path %>
			 </div>
	    </div>
	      	
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			


			<% if signed_in? %>
				<% if current_user.admin? %>
					<div class="navbar-form navbar-left" role="search" style="margin-left: 0em;">
			        <div class="form-group">
						<%= form_tag url_for(:controller => "topics", :action => 'search'),:method => "get", id: "search-form" do %>
		  					<%= text_field_tag :search, params[:search], placeholder: "Search Topics", class: "form-control", style:"width:23.5em; " %>
		  			</div>
		  				<%= button_tag(:name => nil, class: "btn btn-default", style:"margin-top: -15px; padding: 2px 5px 2px 5px; width: 25px; margin-left: -33px; border: white;") do %>
				  				<i class="fa fa-search"></i>
				  				<%end%>
			  				
						<% end %>
					</div> 
				<% else %>

					<div class="navbar-form navbar-left" role="search" style="margin-left: 4em;">
				        <div class="form-group">
							<%= form_tag url_for(:controller => "topics", :action => 'search'),:method => "get", id: "search-form" do %>
			  					<%= text_field_tag :search, params[:search], placeholder: "Search Topics", class: "form-control", style:"width:25em; " %>
			  			</div>
			  				<%= button_tag(:name => nil, class: "btn btn-default", style:"margin-top: -15px; padding: 2px 5px 2px 5px; width: 25px; margin-left: -33px; border: white;") do %>
					  				<i class="fa fa-search"></i>
					  				<%end%>
				  				
							<% end %>
					</div>
				<% end %> 
			<% end %>
	      
	        <ul class="nav navbar-nav navbar-right">
	          <li><%= link_to root_path do %>
					<i class="fa fa-home"></i> Home
				<% end %>
	          </li>
	          <% if signed_in? %>
		          <li><%= link_to like_path do %>
						<i class="fa fa-heart"></i> Favourite
					<% end %>
		          </li>

	          <li><%= link_to tagcloud_path do%>
					<i class="fa fa-tags"></i> Tags
				  <% end %>
	          </li>
	          <% end %>
	          <li><%= link_to help_path do%>
					<i class="fa fa-info-circle"></i> FAQ
				  <% end %>
	          </li>
	          <% if signed_in? %>
	          	<!-- admin only.. need to put if only admin later !!-->
	          	<% if current_user.admin? %>
	          		<li>
	          			<%= link_to users_path do %>
							<i class="fa fa-users"></i> Users
						<% end %>
	          		</li>
	          	<% end %>
	          	<!-- admin only.. need to put if only admin later !!-->
	            <li class="dropdown">
	              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	              		<i class="fa fa-user"></i> Account <b class="caret"></b>
	              </a>
	              <ul class="dropdown-menu">
	                <li><%= link_to current_user do %>
	                	<i class="fa fa-user"></i> Profile
						<% end %>
					</li>
					<% if current_user.admin? %>
						<li><%= link_to boardpanel_path do%>
								<i class="fa fa-bold"></i> Board
							<% end %>
		                </li>
		            <% end %>
	                <li><%= link_to edit_user_path(current_user) do%>
							<i class="fa fa-cog"></i> Setting
						<% end %>
	                </li>
	                <li class="divider"></li>
	                <li>
	                  <%= link_to signout_path, method: "delete" do%>
							<i class="fa fa-sign-out"></i> Sign out
	                  <% end %>
	                </li>
	              </ul>
	            </li>
	          <% else %>
	            <li><%= link_to signin_path do %>
						<i class="fa fa-sign-in"></i> Sign in
					<% end %>
	            </li>
	          <% end %>
	        </ul>
	    </div>
	  </div>
	</div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]--> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  <div class="backgroundimg" style="margin-top:-10px;">
  </div>
  <div class="content-g">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <!-- show information the page you are in and it will only presence only in development phrase-->
	  <%= debug(params) if Rails.env.development? %>
    </div>
  </div>
  </body>
</html>